#
# Documentation
#
# http://about.travis-ci.org/docs/user/languages/ruby
# http://about.travis-ci.org/docs/user/build-configuration
# https://github.com/ruby-amqp/amqp/blob/master/.travis.yml

language: ruby

bundler_args: --without documentation

script: bundle exec rspec

rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - ruby-head
  - rbx-2
  - jruby-head

notifications:
  recipients:
    - james@101ideas.cz
